# Generated by Django 6.0.1 on 2026-01-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(default='sin-email@ejemplo.com', max_length=254)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('tipo_financiamiento', models.CharField(max_length=50)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_meses', models.IntegerField()),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_empleo', models.CharField(max_length=50)),
                ('tiempo_empleo_meses', models.IntegerField()),
                ('consentimiento', models.BooleanField(default=False)),
                ('fecha_consentimiento', models.DateTimeField(blank=True, null=True)),
                ('politica_version', models.CharField(blank=True, max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
