# Generated by Django 6.0.1 on 2026-01-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ciudad',
            field=models.CharField(default='No informada', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nombre',
            field=models.CharField(default='Cliente sin nombre', max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='plazo_meses',
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AlterField(
            model_name='lead',
            name='politica_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefono',
            field=models.CharField(default='No informado', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tiempo_empleo_meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tipo_empleo',
            field=models.CharField(choices=[('clt', 'CLT'), ('autonomo', 'Autónomo'), ('empresario', 'Empresario'), ('desempleado', 'Desempleado')], default='clt', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tipo_financiamiento',
            field=models.CharField(choices=[('inmueble', 'Inmueble'), ('vehiculo', 'Vehículo'), ('personal', 'Crédito personal')], default='inmueble', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='valor_bien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
