# Generated by Django 6.0.1 on 2026-01-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_lead_options_lead_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='valor_bien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
